services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=osoriolzn
      - POSTGRES_PASSWORD=admin1234*
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
